package server;

import java.io.Serializable;
import java.util.ArrayList;

import token.Firefighter;

/**
 * Player class definition.
 * Generated by the TouchCORE code generator.
 */
public class Player implements Serializable {
    
    protected String userName;
    private String password;
    private token.Colour myColour;
//    private Firefighter myFireFighter;
    private ArrayList<Firefighter> myFireFighters;
    private int indexMarker;
    private Integer ID;
    private static final long serialVersionUID = 1L;
    
    public Player(String userName, String password, Integer ID) {
    	this.userName = userName;
    	this.password = password;
    	this.ID = ID;
    	this.myFireFighters = new ArrayList<Firefighter>();
    	this.indexMarker = -1;
    }

    
    /*
     * GETTERS
     */
    public Firefighter getFirefighter() {
    	this.indexMarker++;
    	return this.myFireFighters.get(indexMarker);
    	
    }
    
    public ArrayList<Firefighter> getFirefighters(){
    	return this.myFireFighters;
    }
    
    public token.Colour getColour(){
    	return this.myColour;
    }
    
    public String getUserName() {
        return this.userName;
    }
    
    public boolean validatePassword(String s) {
    	return (s.equals(this.password));
    }
    
    /*
     * SETTERS 
     */
    public void setFirefighter(Firefighter newFirefighter) {
//    	this.myFireFighter = newFirefighter;
    	this.myFireFighters.add(newFirefighter);
    }
    
    
    public void setColour(token.Colour newColour) {
    	this.myColour = newColour;
    }
    
    public Integer getID() {
    	return this.ID;
    }

	@Override
	public String toString() {
		return "Player [userName=" + userName + ", password=" + password + ", myColour=" + myColour.toString() + ", myFireFighter="
				+ myFireFighters.get(0).toString() + ", ID=" + ID + "]";
	}
    
    
}