package Flashpoint;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Action class definition.
 * Generated by the TouchCORE code generator.
 */
public class Action {
    
    protected int APcost;
    
    public void perform() {
        /* TODO: No message view defined */
    }

    public int getCost() {
        /* TODO: No message view defined */
        return 0;
    }

    public boolean validate() {
        /* TODO: No message view defined */
        return false;
    }
}
