package Flashpoint;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Edge class definition.
 * Generated by the TouchCORE code generator.
 */
public class Edge {
    
    public Wall getWall() {
        /* TODO: No message view defined */
        return null;
    }

    public Door getDoor() {
        /* TODO: No message view defined */
        return null;
    }

    public Blank getBlank() {
        /* TODO: No message view defined */
        return null;
    }
}
