package Flashpoint;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * GameManager class definition.
 * Generated by the TouchCORE code generator.
 */
public class GameManager {
    
    public void explosion(Tile target) {
        /* TODO: No message view defined */
    }

    public void resolveFlashOver() {
        /* TODO: No message view defined */
    }

    public void checkKnockDowns() {
        /* TODO: No message view defined */
    }

    public void placePoi() {
        /* TODO: No message view defined */
    }

    public void advanceFire() {
        /* TODO: No message view defined */
    }

    public void takeATurn() {
        /* TODO: No message view defined */
    }

    public Action getAllActions() {
        /* TODO: No message view defined */
        return null;
    }

    public void setup() {
        /* TODO: No message view defined */
    }

    public void play() {
        /* TODO: No message view defined */
    }

    public void saveGame() {
        /* TODO: No message view defined */
    }

    public void setOptions() {
        /* TODO: No message view defined */
    }
}
