package Flashpoint;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * GameState class definition.
 * Generated by the TouchCORE code generator.
 */
public class GameState {
    
    protected int remainingVictims;
    protected int remainingFalseAlarms;
    protected int wallsDamaged;
    protected int lostVictims;
    protected int savedVictims;
    protected int remainingPoi;
    protected int activeFireFighterIndex;
    protected boolean isActiveGame;
    protected Edge[][] matEdges;
    protected Tile[][] matTiles;
    protected int currTile;
    
    public GameState() {
        /* TODO: No message view defined */
    }

    public Tile rollForTile() {
        /* TODO: No message view defined */
        return null;
    }

    public Poi retrievePOI() {
        /* TODO: No message view defined */
        return null;
    }

    public boolean isGameTerminated() {
        /* TODO: No message view defined */
        return false;
    }

    public Tile nextTile() {
        /* TODO: No message view defined */
        return null;
    }

    public int getCurrentPOI() {
        /* TODO: No message view defined */
        return 0;
    }

    public Tile returnTile(int x, int y) {
        /* TODO: No message view defined */
        return null;
    }

    public int getVictims() {
        /* TODO: No message view defined */
        return 0;
    }

    public Firefighter getFireFighterList() {
        /* TODO: No message view defined */
        return null;
    }

    public Firefighter playingFireFighter() {
        /* TODO: No message view defined */
        return null;
    }

    public int getDamageCounter() {
        /* TODO: No message view defined */
        return 0;
    }

    public void updateDamageCounter() {
        /* TODO: No message view defined */
    }

    public void updatePOI() {
        /* TODO: No message view defined */
    }

    public void setSavedCount(int saveCount) {
        /* TODO: No message view defined */
    }

    public void setIsActiveGame(boolean isActiveGame) {
       int x = 2;
    }

    public void placeFireFighter(Firefighter f, Tile t) {
        /* TODO: No message view defined */
    }

    public void initializeTiles(TemplateGame defaultGame) {
        /* TODO: No message view defined */
    }

    public void initializeEdges(TemplateGame defaultGame) {
        /* TODO: No message view defined */
    }

    public void initializeFires(TemplateGame defaultGame) {
        /* TODO: No message view defined */
    }
}
