package Flashpoint;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Lobby class definition.
 * Generated by the TouchCORE code generator.
 */
public class Lobby {
    
    protected boolean isClickable;
    
    public void createNewGame(int numberOfPlayers) {
        
    }
}
