package Flashpoint;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * ParkingSpot class definition.
 * Generated by the TouchCORE code generator.
 */
public class ParkingSpot {
    
    protected Vehicle parkingType;
    
    public ParkingSpot() {
        /* TODO: No message view defined */
    }

    public Vehicle getParkingType() {
        /* TODO: No message view defined */
        return null;
    }
}
