package Flashpoint;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Poi class definition.
 * Generated by the TouchCORE code generator.
 */
public class Poi {
    
    protected boolean revealed;
    protected boolean victim;
    protected boolean isRescued;
    
    public Poi(boolean isVictim) {
        /* TODO: No message view defined */
    }

    public boolean isVictim() {
        /* TODO: No message view defined */
        return false;
    }

    public void reveal() {
        /* TODO: No message view defined */
    }

    public void checkStatus() {
        /* TODO: No message view defined */
    }
}
