package Flashpoint;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Tile class definition.
 * Generated by the TouchCORE code generator.
 */
public class Tile {
    
    protected int fire;
    protected int[] coords;
    protected boolean interior;
    protected Edge[] adjEdges;
    
    public Tile(boolean isParkingspot, int[] coords) {
        /* TODO: No message view defined */
    }

    public void setFire(int amount) {
        /* TODO: No message view defined */
    }

    public int getFire() {
        /* TODO: No message view defined */
        return 0;
    }

    public boolean checkBarriers(int direction) {
        /* TODO: No message view defined */
        return false;
    }

    public boolean containsFF() {
        /* TODO: No message view defined */
        return false;
    }

    public boolean containsPoi() {
        /* TODO: No message view defined */
        return false;
    }

    public Poi[] getPoiList() {
        /* TODO: No message view defined */
        return null;
    }

    public void addPoi(Poi newPoi) {
        /* TODO: No message view defined */
    }

    public Firefighter getFirefighterList() {
        /* TODO: No message view defined */
        return null;
    }

    public Tile getAdjTile(int direction) {
        /* TODO: No message view defined */
        return null;
    }

    public ParkingSpot getNearestAmbulance() {
        /* TODO: No message view defined */
        return null;
    }

    public Edge getEdge(int direction) {
        /* TODO: No message view defined */
        return null;
    }

    public void updateFFList(Firefighter target) {
        /* TODO: No message view defined */
    }

    public int[] getCoords() {
        /* TODO: No message view defined */
        return null;
    }

    public boolean getInterior() {
        /* TODO: No message view defined */
        return false;
    }

    public void updatePoiList(Poi target) {
        /* TODO: No message view defined */
    }

    public void setPoi(Poi target) {
        /* TODO: No message view defined */
    }

    public void setCoords(int[] coords) {
        /* TODO: No message view defined */
    }
}
