package commons.tran.bean;

/**
 * 锟斤拷锟斤拷锟斤拷锟斤拷锟斤拷锟�
 * 
 * @author way
 * 
 */
public enum TranObjectType {
	REGISTER, // 注锟斤拷
	LOGIN, // 锟矫伙拷锟斤拷录
	LOGOUT, // 锟矫伙拷锟剿筹拷锟斤拷录
	FRIENDLOGIN, // 锟斤拷锟斤拷锟斤拷锟斤拷
	FRIENDLOGOUT, // 锟斤拷锟斤拷锟斤拷锟斤拷
	MESSAGE, // 锟矫伙拷锟斤拷锟斤拷锟斤拷息
	UNCONNECTED, // 锟睫凤拷锟斤拷锟斤拷
	FILE, // 锟斤拷锟斤拷锟侥硷拷
	REFRESH,//刷锟铰猴拷锟斤拷锟叫憋拷
	CHOICEA, CHOICEB, CHOICEC, CHOICED, CHOICEE,
	NEXTQ,
	CLOSEQ,
	LOGINSUCCESS,
	CONNECT, SUCCESS, 
	GAMESTATEOUT,
	GAMESTATEUPDATE,
	REGISTERSUCCESS,
	LOBBYCREATION, LOBBYCREATIONSUCCESS, LOBBYUPDATE, 
	FIREFIGHTERPLACEMENT, FFPLACEMENTSUCCESS,
	ACTIONREQUEST, ACTIONSUCCESS,FINDLOBBY,FINDLOBBYSUCCESS,
	CHATMESSAGE,JOINLOBBY,JOINLOBBYSUCCESS, STARTGAMESTATE, STARTGAMESTATESUCCESS, ENDTURN, ENDTURNSUCCESS,
	VEHICLEPLACEMENT, VEHICLEPLACEMENTSUCCESS
}
