package tile;

import token.Vehicle;

/**
 * ParkingSpot class definition.
 * Generated by the TouchCORE code generator.
 */
public class ParkingSpot {
    
    protected Vehicle parkingType;
    
    public ParkingSpot() {
        /* TODO: No message view defined */
    }

    public Vehicle getParkingType() {
        /* TODO: No message view defined */
        return null;
    }
}
