package tile;

import java.util.Arrays;

import token.Vehicle;

/**
 * ParkingSpot class definition.
 * Generated by the TouchCORE code generator.
 * @matekrk
 */
public class ParkingSpot{
    
    protected Vehicle parkingType;
    protected Tile[] tiles;
    boolean isCar;
    
    public ParkingSpot(boolean b, int[] position, Vehicle type) {
    	this.tiles = position;
    	this.parkingType  = type;
    	this.isCar = false;
    }
    
    /*
    public ParkingSpot(boolean isParkingspot, int[] coords, Vehicle vehicleType) {
    	super(isParkingspot, false, coords);
    	this.parkingType = vehicleType;
    }
    */

    /*
     * Getters
     */
    public Vehicle getParkingType() {
        return parkingType;
    }
    public Tile[] getTiles() {
    	return tiles;
    }
    public boolean getCar() {
    	return isCar;
    }
    
    /*
     * Setters
     */
    public void setParkingType(Vehicle parkingType) {
    	this.parkingType = parkingType;
    }
    public void setTiles(Tile[] tiles) {
    	this.tiles = tiles;
    }
    public void setCar(boolean car) {
    	this.isCar = car;
    }

	@Override
	public String toString() {
		return "ParkingSpot [parkingType=" + parkingType + ", tiles=" + Arrays.toString(tiles) + ", car=" + isCar + "]";
	}
    
    
}
