package tile;

import edge.Edge;
import token.Firefighter;
import token.POI;
import game.GameState;

/**
 * Tile class definition.
 * Generated by the TouchCORE code generator.
 */
public class Tile{
    
    protected int fire;
    protected int[] coords;
    protected boolean interior;
    protected Edge[] adjacentEdges;
    protected Firefighter[] listOfFirefighters;
    protected int x;
    protected int y;
    protected POI[] poiList;
    
    public Tile(boolean isParkingspot, int[] coords) {
        /* TODO: No message view defined */
    }

    public void setFire(int amount) {
        /* TODO: No message view defined */
    }

    public int getFire() {
        /* TODO: No message view defined */
        return 0;
    }

    public boolean checkBarriers(int direction) {
        /* TODO: No message view defined */
        return false;
    }

    public boolean containsFF() {
        /* TODO: No message view defined */
        return false;
    }

    public boolean containsPoi() {
        /* TODO: No message view defined */
        return false;
    }

    public POI[] getPoiList() {
        /* TODO: No message view defined */
        return null;
    }

    public void setPOIList(POI[] poiList) {
    	this.poiList = poiList;
    }
    
    public void addPoi(POI newPoi) {
        /* TODO: No message view defined */
    }

    public Firefighter getFirefighterList() {
        /* TODO: No message view defined */
        return null;
    }

    public Tile getAdjTile(int direction) {
        /* TODO: No message view defined */
        return null;
    }

    public ParkingSpot getNearestAmbulance() {
        /* TODO: No message view defined */
        return null;
    }

    public void updateFFList(Firefighter target) {
        /* TODO: No message view defined */
    }

    public int[] getCoords() {
        /* TODO: No message view defined */
        return null;
    }

    public boolean getInterior() {
        /* TODO: No message view defined */
        return false;
    }

    public void updatePoiList(POI target) {
        /* TODO: No message view defined */
    }

    public void setPoi(POI target) {
        /* TODO: No message view defined */
    }

    public void setCoords(int[] coords) {
        /* TODO: No message view defined */
    }
    
    //left: 0, top: 1, right: 2, down: 3
    public Edge getEdge(int direction) {
    	return adjacentEdges[direction];
    }
    
    public int getX() {
    	return x;
    }
    
    public int getY() {
    	return y;
    }
}
