package m5_final;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Firefighter class definition.
 * Generated by the TouchCORE code generator.
 */
public class Firefighter {
    
    protected int AP;
    protected int savedAP;
    protected boolean carryingVictim;
    
    public Firefighter(Player player) {
        /* TODO: No message view defined */
    }

    public void updateLocation(Tile target) {
        /* TODO: No message view defined */
    }

    public int getAP() {
        /* TODO: No message view defined */
        return 0;
    }

    public int getSavedAP() {
        /* TODO: No message view defined */
        return 0;
    }

    public void setAP() {
        /* TODO: No message view defined */
    }

    public void setSavedAP() {
        /* TODO: No message view defined */
    }

    public Tile getCurrentPos() {
        /* TODO: No message view defined */
        return null;
    }

    public boolean getCarrying() {
        /* TODO: No message view defined */
        return false;
    }
}
