package lobby;

// Start of user code for imports
import java.util.*;

import game.FamilyGame;
import game.GameState;
import game.TemplateGame;
import server.Player;
// End of user code

/**
 * Lobby class definition.
 * Generated by the TouchCORE code generator.
 * modified by @matekrk but: ¯\_(ツ)_/¯
 */
public class Lobby {

		protected boolean isClickable;
		// protected GameState gameInstance = new GameState(); @matekrk - game state object is the thing that is currently played. so only 1!
	
		protected int[][] tokenLocations = new int[10][8];
		protected int[][] edgeLocations = new int[30][30] ; 	// subject to change
		protected ArrayList<Player> players;
		protected ArrayList<token.Colour> assignableColours;
		protected String type;
		private TemplateGame template;


		public Lobby(){
			
			//dummy
			players = new ArrayList<Player>();
//			ArrayList<Player> playingPlayers = new ArrayList<Player>(3);
	    	players.add(new Player("Matekrk", "Cuba123"));
	    	players.add(new Player("Zaid", "zeroOneTwoThree"));
	    	players.add(new Player("Tester", "myPassword"));
	    	type = "Family";
	    	if(type.equals("Family")) {
	    		template = new FamilyGame();
	    	}
	    	assignColours();
			
		}

		public void assignColours(){
			assignableColours = new ArrayList<token.Colour>();
			assignableColours.add(token.Colour.GREEN);
			assignableColours.add(token.Colour.BLACK);
			assignableColours.add(token.Colour.WHITE);
			assignableColours.add(token.Colour.RED);
			assignableColours.add(token.Colour.PURPLE);
			assignableColours.add(token.Colour.BLUE);
			for(int i = 0; i<players.size(); i++) {
				if(this.players.get(i) != null) {
					this.players.get(i).setColour(this.assignableColours.get(i));
				}
			}
		}

		public boolean isClickable() {
			return isClickable;
		}


		public void setClickable(boolean isClickable) {
			this.isClickable = isClickable;
		}


		public int[][] getTokenLocations() {
			return tokenLocations;
		}


		public void setTokenLocations(int[][] tokenLocations) {
			this.tokenLocations = tokenLocations;
		}


		public int[][] getEdgeLocations() {
			return edgeLocations;
		}


		public void setEdgeLocations(int[][] edgeLocations) {
			this.edgeLocations = edgeLocations;
		}


		public ArrayList<Player> getPlayers() {
			return players;
		}


		public void setPlayers(ArrayList<Player> players) {
			this.players = players;
		}


		public String getType() {
			return type;
		}


		public void setType(String type) {
			this.type = type;
		}


		public TemplateGame getTemplate() {
			return template;
		}


		public void setTemplete(TemplateGame template) {
			this.template = template;
		}
		
		
}
