package lobby;

// Start of user code for imports
import java.util.*;

import game.GameState;
// End of user code

/**
 * Lobby class definition.
 * Generated by the TouchCORE code generator.
 * not modified by @matekrk because: ¯\_(ツ)_/¯
 */
public class Lobby {
    
    protected boolean isClickable;
    protected GameState gameInsatnce = new GameState();
    
    public void createNewGame(int numberOfPlayers) {
    	
		gameInsatnce.updateGameStateFromTemplate();
    	
    	
    	
    }
}
