package actions;

import edge.Edge;
import tile.Tile;
import token.Firefighter;
import token.Poi;
import game.GameState;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Action class definition.
 * Generated by the TouchCORE code generator.
 * and modified by @matekrk
 */
public abstract class Action {
    
    protected int APcost;
    public void perform() {
        
    }

    public int getCost() {
        /* TODO: No message view defined */
        return APcost;
    }

    public abstract boolean validate() {
        /* TODO: No message view defined */
    }

    boolean removeAvailableActions(GameState a) {
        /* TODO: No message view defined */
        if (a.availableActions.contains(this)) {
        	a.availableActions.remove(this);
        }
        else {
        	return False;
        }
    }

    boolean addAvailableActions(GameState a) {
        /* TODO: No message view defined */
    	a.availableActions.add(this);
        return true;
    }

    Action() {
        /* TODO: No message view defined */
    }

    //WHY HERE
    boolean containsAvailableActions(GameState a) {
        /* TODO: No message view defined */
        return a.availableActions.contains(a);
    }

    int sizeOfAvailableActions(GameState a) {
        /* TODO: No message view defined */
        return a.availableActions.size();
    }

    ArrayList<Action> getAvailableActions() {
        /* TODO: No message view defined */
    	return a.availableActions.size();
    }
}
