package actions;

// Start of user code for imports
import java.util.*;
// End of user code

import game.GameState;
import token.Firefighter;
import tile.Tile;
import edge.Edge;

/**
 * Extinguish class definition.
 * Generated by the TouchCORE code generator.
 * and modified by @matekrk
 */
public class Extinguish extends Action {
    
    protected int direction;
    
    public int getDirection() {
        return direction;
    }

    public boolean validate(GameState gs) {
        boolean flag = false;
        Firefighter playingFirefighter = gs.getPlayingFirefighter();
        int aP = playingFirefighter.getAP();
        Tile currentPosition = playingFirefighter.getCurrentPosition();
        Tile neighbour = gs.getNeighbour(currentPosition, this.direction);
        Edge edge = currentPosition.getEdge(this.direction);
        int fire = neighbour.getFire();
        int cost = super.getCost();
        if (fire >= 1 && fire <= cost) {
            if (currentPosition == neighbour) {
                if (aP >= cost) {
                    flag = true;
                }
            }
        } 
        else {
            //Door typeDoor = edge.getType();
            //Wall typeWall = edge.getType();
            //BlankEdge typeBlank = edge.getType();
            //if (if typeBlank == 'BlankEdge') {
        	if (edge.isBlank()) {
                if (aP >= cost) {
                    flag = true;
                }
            } //else if (if typeDoor = 'Door') {
        	else if (edge.isDoor()) {
                boolean status = edge.getStatus(); //typeDoor.getStatus();
                if (status == true) {
                    if (aP >= cost) {
                        flag = true;
                    }
                }
            } //else if (if typeWall = 'Wall') {
        	else if (edge.isWall()) { 
                int damage = edge.getDamage(); //typeWall.getDamage();
                if (damage == 0) {
                    if (aP >= cost) {
                        flag = true;
                    }
                }
            }
        }
        return flag;
    }

    public void perform(GameState gs) {
        Firefighter playingFirefighter = gs.getPlayingFirefighter();
        int aP = playingFirefighter.getAP();
        playingFirefighter.setSavedAP(aP-this.APcost);
        Tile currentPosition = playingFirefighter.getCurrentPosition();
        Tile neighbour = gs.getNeighbour(currentPosition, direction);
        neighbour.setFire(this.APcost);
    }

	@Override
	public boolean validate() {
		// TODO Auto-generated method stub
		return false;
	}
}
