package actions;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Extinguish class definition.
 * Generated by the TouchCORE code generator.
 * and modified by @matekrk
 */
public class Extinguish extends Action {
    
    protected int direction;
    
    public int getDirection() {
        return direction;
    }

    public boolean validate() {
        boolean flag = false;
        Firefighter playingFirefighter = availableActions.getPlayingFirefighter();
        int aP = playingFirefighter.getAP();
        Tile currPosition = playingFirefighter.getCurrPosition();
        Tile neighbour = currPosition.getNeighbour(this.direction);
        Edge edge = currPosition.getEdge(this.direction);
        int fire = neighbour.getFire();
        int cost = super.getCost();
        if (if fire >= 1 && fire <= cost) {
            if (if currPosition == neighbour) {
                if (if aP >= cost) {
                    flag = true;
                }
            }
        } else if (else) {
            //Door typeDoor = edge.getType();
            //Wall typeWall = edge.getType();
            //BlankEdge typeBlank = edge.getType();
            //if (if typeBlank == 'BlankEdge') {
        	if (edge.isBlank) {
                if (if aP >= cost) {
                    flag = true;
                }
            } //else if (if typeDoor = 'Door') {
        	else if (edge.isDoor)
                boolean status = edge.getStatus(); //typeDoor.getStatus();
                if (if status == 'true') {
                    if (if aP >= cost) {
                        flag = true;
                    }
                }
            } //else if (if typeWall = 'Wall') {
        	else if (edge.isWall) { 
                int damage = edge.getDamage(); //typeWall.getDamage();
                if (if damage == 0) {
                    if (if aP >= cost) {
                        flag = true;
                    }
                }
            }
        }
        return flag;
    }

    public void perform() {
        Firefighter playingFirefighter = availableActions.getPlayingFirefighter();
        int aP = playingFirefighter.getAP();
        playingFirefighter.setSavedAP();
        Tile currPosition = playingFirefighter.getCurrPosition();
        Tile neighbour = currPosition.getNeighbour(this.direction);
        neighbour.setFire(this.APcost);
    }
}
