package m5_final;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * vehicle class definition.
 * Generated by the TouchCORE code generator.
 */
public class vehicle {
    
    protected int direction;
    
    public int getDirection() {
        /* TODO: No message view defined */
        return 0;
    }

    public void perform() {
        /* TODO: No message view defined */
    }

    public boolean validate() {
        /* TODO: No message view defined */
        return false;
    }
}
