package tile;

import token.Vehicle;

/**
 * ParkingSpot class definition.
 * Generated by the TouchCORE code generator.
 */
public class ParkingSpot extends Tile{
    
    protected Vehicle parkingType;
    
    public ParkingSpot(boolean isParkingspot, int[] coords, Vehicle vehicleType) {
    	super(isParkingspot, false, coords);
    	this.parkingType = vehicleType;
    }

    public Vehicle getParkingType() {
        /* TODO: No message view defined */
        return null;
    }
}
