package server;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Player class definition.
 * Generated by the TouchCORE code generator.
 */
public class Player {
    
    protected String userName;
    private String password;
    
    /*
     * GETTERS
     */
    
    public String getUserName() {
        return this.userName;
    }
    
    public boolean validatePassword(String s) {
    	return (s.equals(this.password));
    }
}
