package game;

/**
 * TemplateGame class definition.
 * Generated by the TouchCORE code generator.
 */
abstract public class TemplateGame {
    
    protected int nbFires;
    protected int nbPoi;
    protected int nbVictims;
    protected int[][] fireLocation;
    
    public TemplateGame(/*File?*/) {
        /* TODO: No message view defined */
    }

    public int[][] getFireLocation() {
        /* TODO: No message view defined */
        return null;
    }

    public int getNbFire() {
        /* TODO: No message view defined */
        return 0;
    }
}
