package game;

import java.io.Serializable;

/**
 * TemplateGame class definition.
 * Generated by the TouchCORE code generator.
 */
abstract public class TemplateGame implements Serializable {
     
    /*protected int nbFires;
    protected int nbPoi;
    protected int nbVictims;*/

	protected int[][] fireLocationAndPOILocations;
    protected int[][] edgeLocations;
    private static final long serialVersionUID = 1L;
    
    public abstract int[][] getPOILocations();
    
    public abstract int[][] getFireLocations();
    
    public abstract int[][] getEdgeLocations();
}
