package edge;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Blank class definition.
 * Generated by the TouchCORE code generator.
 */
public class Blank {
    
    public Blank() {
        /* TODO: No message view defined */
    }
    
    /*
     * Questions
     */
    
    public boolean isBlank() {
    	return true;
    }
}
