package edge;

/**
 * Blank class definition.
 * Generated by the TouchCORE code generator.
 */
public class Blank extends Edge{
    
    public Blank() {
        /* TODO: No message view defined */
    }
    
    /*
     * Questions
     */
    
    public boolean isBlank() {
    	return true;
    }
    
    @Override
	public String toString() {
		return "Blank []";
	}

	@Override
	public boolean getStatus() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public int getDamage() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void chop() {
		// TODO Auto-generated method stub
		
	}
	
	@Override
	public void build() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void destroyDoor() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void destroyWall() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void change() {
		// TODO Auto-generated method stub
		
	}
	
   public boolean isDestroyed() {
        return false;
    }
}
