package edge;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Door class definition.
 * Generated by the TouchCORE code generator.
 * and modified by @matekrk
 */
public class Door extends Edge{
    
    protected boolean destroyed;
    protected boolean isOpen;
    
    public Door() {
        /* TODO: No message view defined */
    	this.isOpen = false;
    	this.destroyed = false;
    }

    /*
     * GETTERS
     */
    
    public boolean isDestroyed() {
        return destroyed;
    }

    public boolean getStatus() {
        return isOpen;
    }
    
    /*
     * SETTERS
     */
    
    
    public void destroyDoor() {
        destroyed = true;
    }

    public void change() {
        isOpen = !isOpen;
    }
    
    /*
     * Questions
     */
    
    public boolean isDoor() {
    	return true;
    }
    
    public Door getDoor() {
        return this;
    }

	@Override
	public String toString() {
		return "Door [destroyed=" + destroyed + ", isOpen=" + isOpen + "]";
	}

	@Override
	public int getDamage() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void chop() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void destroyWall() {
		// TODO Auto-generated method stub	
	}
}
