package edge;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Door class definition.
 * Generated by the TouchCORE code generator.
 * and modified by @matekrk
 */
public class Door {
    
    protected boolean destroyed;
    protected boolean isOpen;
    
    public Door() {
        /* TODO: No message view defined */
    }

    /*
     * GETTERS
     */
    
    public boolean isDestroyed() {
        return destroyed;
    }

    public boolean getStatus() {
        return isOpen;
    }
    
    /*
     * SETTERS
     */
    
    public void destroyDoor() {
        destroyed = true;
    }

    public void change() {
        isOpen = !isOpen;
    }
    
    /*
     * Questions
     */
    
    public boolean isDoor() {
    	return true;
    }
    
    public Door getDoor() {
        return this;
    }

	@Override
	public String toString() {
		return "Door [destroyed=" + destroyed + ", isOpen=" + isOpen + "]";
	}
}
