package edge;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Door class definition.
 * Generated by the TouchCORE code generator.
 * and modified by @matekrk
 */
public class Door {
    
    protected boolean destroyed;
    protected boolean isOpen;
    
    public Door() {
        /* TODO: No message view defined */
    }

    public boolean isDestroyed() {
        /* TODO: No message view defined */
        return false;
    }

    public boolean destroyDoor() {
        /* TODO: No message view defined */
        return false;
    }

    public boolean getStatus() {
        /* TODO: No message view defined */
        return false;
    }

    public void change() {
        /* TODO: No message view defined */
    }
    
    public boolean isDoor() {
    	return true;
    }
    
    public Door getDoor() {
        return this;
    }
}
