package edge;

// Start of user code for imports
import java.util.*;
import tile.Tile;
// End of user code

/**
 * Edge class definition.
 * Generated by the TouchCORE code generator.
 * and modified by @matekrk
 */
public abstract class Edge {
    
    // MODIFIED - earlier it was public Wall getWall <- not natural with inheritance (but natural with touchcore)
	
    private Tile[] tiles;
    
    /*
     * Getters
     */
    
    public Tile[] getTiles() { //do we need that?
    	return tiles;
    }
    
    /*
     * Questions
     */
    
    public boolean isWall() {
    	return false;
    }
    public boolean isDoor() {
    	return false;
    }
    public boolean isBlank() {
    	return false;
    }
    
    public abstract boolean getStatus();
    public abstract int getDamage();
    public abstract void chop();
    
}
