package m5_final;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Edge class definition.
 * Generated by the TouchCORE code generator.
 * and modified by @matekrk
 */
public abtract class Edge {
    // THIS IS HOW IT WAS:
    public Wall getWall() {
        /* TODO: No message view defined */
        return null;
    }

    public Door getDoor() {
        /* TODO: No message view defined */
        return null;
    }

    public Blank getBlank() {
        /* TODO: No message view defined */
        return null;
    }
    // THIS IS HOW IT IS GONNA BE:
    private Tile[] tiles;
    public Tile[] getTiles() { //do we need that?
    	return tiles;
    }
    public boolean ifWall() {
    	return false;
    }
    public boolean ifDoor() {
    	return false;
    }
    public boolean ifBlank() {
    	return false;
    }
    
}
