package edge;

// Start of user code for imports
import java.util.*;
import tile.Tile;
// End of user code

/**
 * Edge class definition.
 * Generated by the TouchCORE code generator.
 * and modified by @matekrk
 */
public abstract class Edge {
    // THIS IS HOW IT WAS:
    public Wall getWall() {
        /* TODO: No message view defined */
        return null;
    }

    public Door getDoor() {
        /* TODO: No message view defined */
        return null;
    }

    public Blank getBlank() {
        /* TODO: No message view defined */
        return null;
    }
    // THIS IS HOW IT IS GONNA BE:
    private Tile[] tiles;
    public Tile[] getTiles() { //do we need that?
    	return tiles;
    }
    public boolean isWall() {
    	return false;
    }
    public boolean isDoor() {
    	return false;
    }
    public boolean isBlank() {
    	return false;
    }
    
    public abstract boolean getStatus();
    public abstract int getDamage();
    public abstract void chop();
    
}
