package edge;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Wall class definition.
 * Generated by the TouchCORE code generator.
 * and modified by @matekrk
 */
public class Wall extends Edge{
    
    protected int damage; //domain: 0,1,2
    
    public Wall() {
    	this.damage = 0;
    }
    
    public Wall(int damage) {
    	this.damage = damage;
    }

    /*
     * Getters
     */
    
    public int getDamage() {
        return damage;
    }
    
    /*
     * Setters
     */
    
    //always chopping by 1
    public void chop() {
        if (damage > 0) {
        	damage--;
        }
    }


    public void destroyWall() {
        damage = 0;
    }
    
    /*
     * Questions
     */
    
    public boolean isWall() {
    	return true;
    }
    
    public Wall getWall() {
        return this;
    }
    
	@Override
	public boolean getStatus() {
		// TODO Auto-generated method stub
		return false;
	}
}
