package m5_final;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Wall class definition.
 * Generated by the TouchCORE code generator.
 */
public class Wall {
    
    protected int damage;
    
    public Wall() {
        /* TODO: No message view defined */
    }

    public void chop() {
        /* TODO: No message view defined */
    }

    public int getDamage() {
        /* TODO: No message view defined */
        return 0;
    }

    public void destroyWall() {
        /* TODO: No message view defined */
    }
}
