package edge;

// Start of user code for imports
import java.util.*;
import tile.Tile;
// End of user code

/**
 * Edge class definition.
 * Generated by the TouchCORE code generator.
 * and modified by @matekrk
 */
public abstract class Edge {
    
    // MODIFIED - earlier it was public Wall getWall <- not natural with inheritance (but natural with touchcore)
	
    private Tile[] tiles;
    
    /*
     * Getters
     */
    
    public Tile[] getTiles() { //do we need that?
    	return tiles;
    }
    
    /*
     * Questions
     */
    
    public boolean isWall() {	//change these to getType and alter classes accordingly?
    	return false;
    }
    public boolean isDoor() {
    	return false;
    }
    public boolean isBlank() {
    	return false;
    }
    
    
    public abstract boolean getStatus();    
    public abstract int getDamage();	//If getType done properly, then in if/else checks we can intialize of that object and then make edge specific checks
    									//wouldn't need to declare edge specific methods here								
    public abstract void chop();
    public abstract void destroyDoor();
    public abstract void destroyWall();
    public abstract void change();
    
}
